;*******************************************************************************
                    #RAM
;*******************************************************************************

onoff               rmb       1
ptbd_temp           rmb       1
ptbdd_temp          rmb       1
debounce            rmb       1
previous_state      rmb       1
press_value         rmb       1
temp_ones           rmb       1
temp_tens           rmb       1
a_temp              rmb       1
a_tens              rmb       1
a_ones              rmb       1
b_time_h            rmb       1
b_time_t            rmb       1
b_time_o            rmb       1
b_time_total        rmb       1
b_state             rmb       1
cntr5               rmb       1
cntr6               rmb       1
cntr7               rmb       1
seconds_temp        rmb       1
c_temp              rmb       1
c_hold              rmb       1
mask                rmb       1
cntr3               rmb       1
mask_2              rmb       1
month_t             rmb       1
cntr4               rmb       1
cur_counts          rmb       1
date_t              rmb       1
send                rmb       1
hundreds            rmb       1
seconds             rmb       1
update              rmb       1
year_t              rmb       1
col_mask            rmb       1
hour_t              rmb       1
minutes             rmb       1
tens                rmb       1
hours               rmb       1
min_t               rmb       1
ones                rmb       1
col1                rmb       1
date                rmb       1
sec_t               rmb       1
tenths              rmb       1
col2                rmb       1
intacc1             rmb       4
month               rmb       1
col3                rmb       1
intacc2             rmb       4
year                rmb       1
col4                rmb       1
ext_temp            rmb       2
read_data           rmb       1
press_pound         rmb       1
send_data           rmb       1
total_temp          rmb       2
count_temp          rmb       2
loop_value          rmb       1
final_temp          rmb       2
loop_value_2        rmb       1
cntr1               rmb       1
temp_msb            rmb       1
cntr2               rmb       1
temp_lsb            rmb       1
highbyte            rmb       1
n                   rmb       1
lowbyte             rmb       1
m                   rmb       1
state               rmb       1
pwm                 rmb       1
data                rmb       1

;*******************************************************************************
                    #ROM
;*******************************************************************************
